Release waiters on close
dropbox/kafka pull request #41
Opened 2017-04-25 20:59 UTC by DrTall

This diff also upgrades the periodic metadata refresh into an actual Fetch call. This means that if the change in connection.go doesn't actually fix the issue, we should still be able to get fresh metadata every hour (the default for the refresh period).

2017-04-25 21:19 UTC, zorkian requested changes
Mm. I'm not sure if this actually adds anything, I just was digging through the code because I felt like this would be a bigger issue if we weren't closing them and saw:

https://github.com/DrTall/kafka/blob/fd7a132b5bbbbbc5845408b6bbb6662b3dd02878/connection.go#L83

So, the `Close` method invokes close on the TCPConnection object which then causes `readRespLoop` to break its receive loop, which then invokes the defer which closes everybody who's waiting?

Also, the `Fetch` method just returns the metadata but since you invoked it in a goroutine it's a no-op? Might as well not do it? `Refresh` is the only method that actually updates the metadata in the broker object.

2017-04-25 21:35 UTC, DrTall commented
Hmmm okay so we think that closing the connection closing the `rw` net connection which causes `proto.ReadResp` to return an error which causes that loop to exit? If that's the case, then I guess the connection isn't being closed and the call has just been abandoned.

So maybe it is simplest just to address this by putting a timeout in `Refresh`? I think that would most obviously fix this issue although it may leave something lurking for other users of connection :-/

2017-04-27 06:39 UTC, zorkian commented
Yeah, this is awkward.

So, suggestion: given that Kafka connections are serial, and given that our connection pool behavior now guarantees we never have concurrent requests on a connection, why don't we just give up on the whole way it works right now?

I.e., I just opened #42 take a look?

Note this doesn't solve your problem. I suspect the next step, if you like this, is to figure out how to add a timeout on the `proto.ReadResp` function and if we exceed that timeout to fail so the upstream knows to retry/throw an error. I think this would be marginally nicer than having the metadata refresher have a timeout, but I am not opposed to that idea.

2017-04-27 20:00 UTC, DrTall commented
Great, how about we try canary your diff for a bit and then yes I agree that this will be a lot more straightforward to implement a timeout in our connection itself and thereby fix all the calls not just metadata.

2017-05-26 17:42 UTC, closed without merging